//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LmpSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public int PostId { get; set; }
        public int InvoiceId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public int Quality { get; set; }
        public int UnitPrice { get; set; }
        public int Bill { get; set; }
        public string COD { get; set; }
        public bool Paid { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> LastModifiedOnDate { get; set; }
        public int LastModifiedByUserId { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Post Post { get; set; }
    }
}
