//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LmpSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserScore
    {
        public int Id { get; set; }
        public Nullable<int> PostId { get; set; }
        public Nullable<int> LessonId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string TestDetail { get; set; }
        public int TrueNumberAnswer { get; set; }
        public Nullable<int> TotalNumberQuestion { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
    }
}
